"""vyperling.runnergen — generate a Unity test runner (main) for a test file.

Ceedling/CMock-style test files declare ``void test_*(void)`` functions but no
``main``. Ceedling auto-generates a runner that calls ``RUN_TEST`` for each. This
module reproduces that: it scans a test file for test functions and emits a small
``*_runner.c`` translation unit providing ``main`` + ``UNITY_BEGIN/END``.
"""

from __future__ import annotations

import re
from pathlib import Path

def _test_func_re(test_prefix: str, test_naming: str) -> re.Pattern:
    """Build the regex that finds test function definitions for the given conventions.

    camelCase mode matches both the exact prefix and its lowercase variant so that
    Ceedling projects with file prefix ``Test`` but function prefix ``test`` work
    without extra config.
    """
    if test_naming == "camelCase":
        p = re.escape(test_prefix)
        p_lower = re.escape(test_prefix[0].lower() + test_prefix[1:])
        if p == p_lower:
            name_pat = rf"{p}[A-Za-z0-9_]+"
        else:
            name_pat = rf"(?:{p}|{p_lower})[A-Za-z0-9_]+"
    else:
        p = re.escape(test_prefix)
        name_pat = rf"{p}[A-Za-z0-9_]+"
    return re.compile(
        rf"^[ \t]*void[ \t]+({name_pat})[ \t]*\([ \t]*(?:void)?[ \t]*\)",
        re.MULTILINE,
    )


def extract_tests(
    test_file: Path,
    test_prefix: str = "test_",
    test_naming: str = "snake_case",
) -> list[str]:
    """Return the ordered, de-duplicated list of test function names."""
    try:
        text = test_file.read_text(encoding="utf-8")
    except OSError:
        return []
    pattern = _test_func_re(test_prefix, test_naming)
    seen: list[str] = []
    for name in pattern.findall(text):
        if name not in seen:
            seen.append(name)
    return seen


def _has_symbol(text: str, symbol: str) -> bool:
    return re.search(rf"\b{symbol}\b[ \t]*\(", text) is not None


def render_runner(
    test_file: Path,
    tests: list[str],
    mocks: list[str] | None = None,
    mock_prefix: str = "mock_",
) -> str:
    """Render the runner C source for the given test file, tests, and mocks."""
    mocks = mocks or []
    try:
        text = test_file.read_text(encoding="utf-8")
    except OSError:
        text = ""

    has_setup = _has_symbol(text, "setUp")
    has_teardown = _has_symbol(text, "tearDown")
    has_suite_setup = _has_symbol(text, "suiteSetUp")
    has_suite_teardown = _has_symbol(text, "suiteTearDown")

    lines: list[str] = [
        "/* Auto-generated by vyperling. DO NOT EDIT. Unity + CMock-lifecycle runner. */",
        '#include "unity.h"',
    ]
    for m in mocks:
        lines.append(f'#include "{mock_prefix}{m}.h"')
    lines.append("")
    # setUp/tearDown are defined in the test TU; default to no-ops if absent.
    if not has_setup:
        lines.append("void setUp(void) {}")
    if not has_teardown:
        lines.append("void tearDown(void) {}")
    lines.append("")
    for name in tests:
        lines.append(f"void {name}(void);")
    lines.append("")
    if has_suite_setup:
        lines.append("extern void suiteSetUp(void);")
    if has_suite_teardown:
        lines.append("extern int suiteTearDown(int num_failures);")
    lines.append("")
    # Per-test CMock lifecycle wrapper (mirrors Ceedling's generated runner):
    # mock_*_Init -> setUp -> test -> tearDown -> mock_*_Verify -> mock_*_Destroy.
    lines.append("static void cmock_mocks_init(void)")
    lines.append("{")
    for m in mocks:
        lines.append(f"    {mock_prefix}{m}_Init();")
    lines.append("}")
    lines.append("static void cmock_mocks_verify(void)")
    lines.append("{")
    for m in mocks:
        lines.append(f"    {mock_prefix}{m}_Verify();")
    lines.append("}")
    lines.append("static void cmock_mocks_destroy(void)")
    lines.append("{")
    for m in mocks:
        lines.append(f"    {mock_prefix}{m}_Destroy();")
    lines.append("}")
    lines.append("")
    lines.append(
        "static void run_test(UnityTestFunction func, const char *name, UNITY_LINE_TYPE line)"
    )
    lines.append("{")
    lines.append("    Unity.CurrentTestName = name;")
    lines.append("    Unity.CurrentTestLineNumber = line;")
    lines.append("    Unity.NumberOfTests++;")
    lines.append("    UNITY_CLR_DETAILS();")
    lines.append("    if (TEST_PROTECT()) {")
    lines.append("        cmock_mocks_init();")
    lines.append("        setUp();")
    lines.append("        func();")
    lines.append("    }")
    lines.append("    if (TEST_PROTECT()) {")
    lines.append("        tearDown();")
    lines.append("        cmock_mocks_verify();")
    lines.append("    }")
    lines.append("    cmock_mocks_destroy();")
    lines.append("    UnityConcludeTest();")
    lines.append("}")
    lines.append("")
    lines.append("int main(void)")
    lines.append("{")
    if has_suite_setup:
        lines.append("    suiteSetUp();")
    lines.append(f'    UnityBegin("{test_file.name}");')
    for name in tests:
        lines.append(f'    run_test({name}, "{name}", __LINE__);')
    if has_suite_teardown:
        lines.append("    return suiteTearDown(UnityEnd());")
    else:
        lines.append("    return UnityEnd();")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_runner(
    test_file: Path,
    out_path: Path,
    mocks: list[str] | None = None,
    test_prefix: str = "test_",
    test_naming: str = "snake_case",
    mock_prefix: str = "mock_",
) -> tuple[Path, list[str]]:
    """Write the runner for ``test_file`` to ``out_path`` (only if changed).

    Returns ``(out_path, test_names)``.
    """
    tests = extract_tests(test_file, test_prefix, test_naming)
    content = render_runner(test_file, tests, mocks, mock_prefix)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if not out_path.is_file() or out_path.read_text(encoding="utf-8") != content:
        out_path.write_text(content, encoding="utf-8")
    return out_path, tests
